### ISSUE TITLE
`glide create` followed by `glide init` results in `Lock file does not match YAML configuration`

### ISSUE THREAD

**Issue by tamird** [Masterminds/glide#198] opened 2015-12-29 19:24 UTC
Tested on https://github.com/cockroachdb/cockroach-prod

[glide.lock.txt](https://github.com/Masterminds/glide/files/74281/glide.lock.txt)
[glide.yaml.txt](https://github.com/Masterminds/glide/files/74282/glide.yaml.txt)

**Comment by mattfarina** [comment] 2015-12-30 00:45
@tamird what version of Glide are you using (`glide --version`), what OS are you on, and can you share your environment (`go env`)? This will help me in reproducing the issue.

**Comment by tamird** [comment] 2015-12-30 00:47
```
$ glide --version
glide version 0.8.2
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tamird/src/go"
GORACE=""
GOROOT="/Users/tamird/src/go1.5"
GOTOOLDIR="/Users/tamird/src/go1.5/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
$ uname -a
Darwin Tamirs-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

**Comment by mattfarina** [comment] 2015-12-30 00:55
@tamird thanks for the incredibly fast reply.

I think that was fixed in #185 and #187. Using the tip of master I'm not able to reproduce the problem. I'm shooting for a 0.8.3 release tomorrow with the fix in it.

Can you test the tip of master?

**Comment by tamird** [comment] 2015-12-30 01:05
Yep, seems fixed on master.

**Comment by mattfarina** [comment] 2015-12-30 03:27
@tamird Great. I'll be release 0.8.3 tomorrow (Wednesday) with this fix in it.

**Closed by mattfarina** 2015-12-30 03:27 UTC
Labels: duplicate
