### ISSUE TITLE
Update just one repo

### ISSUE THREAD

**Issue by kenkouot** [Masterminds/glide#474] opened 2016-06-15 18:46 UTC
There seems to be conflicting information from #92 and the official Glide documentation/cli help. Is there currently anyway to update just one repository using Glide?

Running `glide update github.com/foo/bar` doesn't seem to update that one repository.

I've been manually replacing hashes in my lock file and running `glide install` to get the desired outcome. Would love to know a better way, if there is one.

**Comment by sdboyer** [comment] 2016-06-15 19:01
Yeah, there's a lot of discussion around this. Probably the best issue for the full view of what's upcoming is #252 . tl;dr - it's very much a planned feature, but one that will likely only get here once the new engine is in place.

till then...well, yeah, I do that same, awkward hash editing thing that you do 😦

**Comment by atombender** [comment] 2016-06-16 18:22
This should closed in favour of #252.

**Comment by technosophos** [comment] 2016-06-16 18:47
Closed as a duplicate of #252

**Closed by technosophos** 2016-06-16 18:47 UTC
Labels: duplicate
