### ISSUE TITLE
glide ignore packages in test files

### ISSUE THREAD

**Issue by hvnsweeting** [Masterminds/glide#103] opened 2015-10-12 07:50 UTC
when I run glide guess/glide pin, they showed list of packages but missing those that I use for *_test.go.
Is that a feature or should it be fixed?

Thanks

**Comment by mattfarina** [comment] 2015-10-12 17:26
I had not thought about this before. What's happening here is the `go/build` package has two separate things for imports. `Imports` is for your code and `TestImports` is for any imports in test code. We are just using the former and end up missing test imports.

Should test imports be on the `Imports` list in the yaml file or should they be on `devImports`?

@technosophos any thoughts on this?

**Comment by technosophos** [comment] 2015-10-12 18:04
My initial intent when I added `devImports` was for test and build dependencies.

**Comment by davecgh** [comment] 2015-12-29 23:49
I see the opposite with https://github.com/syndtr/goleveldb.  There are several dependencies that are only needed to run the tests which are included in the `imports` section of the lock file.

Glide should gain a `-t` flag (or an aptly named option in the yaml) just like `go get` has in my opinion.  Specifically:

```
The -t flag instructs get to also download the packages required to build
the tests for the specified packages.
```

One of the primary purposes of glide is, of course, to provide reproducible builds and installs to end user and developers alike.  To that end, testing of dependencies is squarely aimed more at developers than end users and thus should really be opt-in with a flag/optional keyword, just like `go get` does it.  A normal end user will typically want to the produce the final stable binary without needing or wanting to download the additional packages only needed for testing, particularly of dependencies.

It is slightly debatable whether the test-only dependencies of the project itself are included by default, but packages only required by the tests in dependencies should most definitely not be.

**Comment by krancour** [comment] 2016-03-05 16:57
I am running into this as well.  I have a project of _just_ integration tests written in go.

My workaround has been to include a dummy non-test file that looks like this:

```
package tests

import (
	// This is a workaround for the fact that glide seems not to recursively resolve packages needed
	// only for testing.
	_ "k8s.io/kubernetes/pkg/client/unversioned"
)

```

But I'd rather not have to do that, obviously.

**Comment by mattfarina** [comment] 2016-03-08 16:53
I've added #320 to track resolving test imports.

**Comment by mattfarina** [comment] 2016-06-18 01:37
Please see #461 which is trying to fix the management of test imports. Reviews appreciated.

**Comment by mattfarina** [comment] 2016-06-21 14:32
Fixed. Tip of master now handles test imports.

**Closed by mattfarina** 2016-06-21 14:32 UTC
