### ISSUE TITLE
How to ignore example directory?

### ISSUE THREAD

**Issue by netroby** [Masterminds/glide#164] opened 2015-12-14 03:38 UTC
There may be many example code in third party library. but we did not to including them in our main project. we even do not need more and more dependencies about the example code.
For example

```
https://github.com/gin-gonic/contrib/blob/master/sessions/examples/example_redis.go
```

The example code need redis, but we not using redis. so we can just ommit it

**Comment by netroby** [comment] 2015-12-14 03:40
```
huzhifeng@s ~/go/src/github.com/netroby/gosense (master*) $ glide list
[ERROR] Could not find /home/huzhifeng/go/src/github.com/netroby/gosense/vendor/github.com/gin-gonic/contrib/sessions/examples: found packages maincookie (example_cookie.go) and mainredis (example_redis.go) in /home/huzhifeng/go/src/github.com/netroby/gosense/vendor/github.com/gin-gonic/contrib/sessions/examples
[ERROR] Dependency /home/huzhifeng/go/src/github.com/netroby/gosense/vendor/github.com/gin-gonic/contrib/sessions failed to resolve: found packages maincookie (example_cookie.go) and mainredis (example_redis.go) in /home/huzhifeng/go/src/github.com/netroby/gosense/vendor/github.com/gin-gonic/contrib/sessions/examples.
Oops! found packages maincookie (example_cookie.go) and mainredis (example_redis.go) in /home/huzhifeng/go/src/github.com/netroby/gosense/vendor/github.com/gin-gonic/contrib/sessions/examples

```

**Comment by mattfarina** [comment] 2015-12-14 14:19
Good question. Right now the `ignore` property in the `glide.yaml` file is a list of packages to ignore. For example,

```yaml
ignore:
- github.com/Masterminds/vcs
- gopkg.in/yaml.v2
```

Does that solve your problem?

@technosophos it may be a good idea to add a way to ignore directories in the local project.

**Comment by technosophos** [comment] 2015-12-14 16:11
These directories are supposed to be prefixed with `_` (e.g. `_examples`). But I know you can't always get repo owners to change that. The best solution is to use the `ignore` property.

@mattfarina I'm not sure what you mean.

**Comment by baliw** [comment] 2015-12-31 06:42
@mattfarina @technosophos 

We could really use a way to ignore directories in dependencies.

I'm trying to use [Echo](https://github.com/labstack/echo) and it has a `recipes` directory that ends up causing all kinds of dependencies to get loaded that I don't need.

I tried the "ignore:" trick but it's long and didn't seem to work anyway.   Also, I have to keep updating that as the project ads more examples.

      - package: github.com/labstack/echo
        vcs: git
        ignore:
          - github.com/akavel/rsrc
          - github.com/astaxie/beego
          - github.com/beego/goyaml2
          - github.com/BurntSushi/toml
          - github.com/codegangsta/negroni
          - github.com/codegangsta/inject
          - github.com/bradfitz/gomemcache
          - github.com/beego/x2j
          - github.com/belogik/goes
          - github.com/clbanning/x2j
          - github.com/boltdb/bolt
          - github.com/couchbaselabs/go-couchbase
          - github.com/dgrijalva/jwt-go
          - github.com/daaku/go.zipexe
          - github.com/couchbase/gomemcached
          - github.com/couchbase/cbauth
          - github.com/couchbase/go-couchbase
          - github.com/cupcake/rdb
          - github.com/couchbaselabs/go_n1ql
          - github.com/dustin/go-broadcast
          - github.com/edsrzf/mmap-go
          - github.com/facebookgo/clock
          - github.com/facebookgo/stats
          - github.com/facebookgo/httpdown
          - github.com/facebookgo/grace
          - github.com/garyburd/redigo
          - github.com/GeertJohan/go.incremental
          - github.com/GeertJohan/go.rice
          - github.com/gin-gonic/gin
          - github.com/go-martini/martini
          - github.com/go-sql-driver/mysql
          - github.com/goji/param
          - github.com/gocraft/web
          - github.com/golang/snappy
          - github.com/golang/protobuf
          - github.com/gorilla/websocket
          - github.com/jessevdk/go-flags
          - github.com/julienschmidt/httprouter
          - github.com/justinas/alice
          - github.com/kardianos/osext
          - github.com/lib/pq
          - github.com/manucorporat/sse
          - github.com/manucorporat/stats
          - github.com/martini-contrib/render
          - github.com/mattn/go-colorable
          - github.com/mattn/go-isatty
          - github.com/onsi/ginkgo
          - github.com/oxtoacart/bpool
          - github.com/onsi/gomega
          - github.com/peterh/liner
          - github.com/Pallinder/go-randomdata
          - github.com/rs/cors
          - github.com/rs/xhandler
          - github.com/siddontang/goredis
          - github.com/siddontang/go
          - github.com/siddontang/ledisdb
          - github.com/siddontang/rdb
          - github.com/speps/go-hashids
          - github.com/stretchr/objx
          - github.com/stretchr/testify
          - github.com/syndtr/goleveldb
          - github.com/thoas/stats
          - github.com/ugorji/go
          - github.com/zenazn/goji
          - github.com/tylerb/graceful
          - github.com/wendal/errors
          - golang.org/x/crypto
          - golang.org/x/net
          - golang.org/x/text
          - gopkg.in/bluesuncorp/validator.v5

**Comment by mattfarina** [comment] 2016-02-04 15:57
With the merge of #240, which will be happening soon, Glide can walk just the imports being used and include those rather than walking the whole possible tree.

**Comment by mattfarina** [comment] 2016-02-04 17:59
One master Glide only walks the packages used by a project instead of all the packages possible. Does that fix the problem?

**Comment by dmitris** [comment] 2016-02-15 11:50
is there a documentation on the ignore property -  how it works and what exactly gets ignored?  I'm trying to make glide skip including an unnecessary dependency (dependency of a "root" package when only a small dependency-light subpackage is needed), the `glide update` does say: `[INFO] Ignoring: go.corp.sometld.com/org/repo` but that package is still being included in glide.lock and checked out into the vendor/ directory.  The "ignoring" [INFO] message also comes after the one saying that the package you want to ignore is being fetched into `vendor`.  Is it the expected behavior?

**Comment by mattfarina** [comment] 2016-02-16 17:29
@dmitris what version of Glide are you using? The behavior is [documented on RTD](http://glide.readthedocs.org/en/latest/glide.yaml/).

**Comment by fschl** [comment] 2016-03-05 16:13
We haven a similar issue using the latest dev version (master branch) of glide for public go packages.
The build system puts our private go dependencies inside the vendor directory. After that, glide is supposed to install the publicly available packages. At this point, glide is supposed to ignore our private packages.

`glide.yaml` looks sth. like this:

```
package: gitlab.corp.com/org/package-to-build
ignore:
  - gitlab.corp.com/org/repo1
  - gitlab.corp.com/org/repo1/vendor
  - gitlab.corp.com/org/repo2/
  - gitlab.corp.com/org/repo2/subpackage
```
When doing `glide install` public packages get installed correctly, and ignored packages are flagged as such:
```
[INFO] Resolving imports
[INFO] Ignoring: gitlab.opendriverslog.de/odl/goodl-lib/dbg
```
But after this message:
`[INFO] Downloading dependencies. Please wait...`

it still tries to update the ignored packages:

```
[ERROR] Update failed for gitlab.corp.com/org/repo1: Cannot detect VCS
[WARN] Unable to checkout gitlab.corp.com/org/repo1
```
which results in a failing build.

I am currently looking into that.

**Comment by mattfarina** [comment] 2016-03-14 13:58
@fschl There was a bug with ignored packages. Version 0.9.3, that was released last week, fixed the bug. Can you try again?

**Comment by fschl** [comment] 2016-03-15 20:40
@mattfarina You should rather ask @dmitris if he still has problems.
My issue was fixed, when you merged my PR #305  ;-)

**Comment by mattfarina** [comment] 2016-03-16 13:35
@dmitris are you still having issues.

Note, #334 is currently in progress to exclude directories from the local codebase from scanning.

**Comment by dmitris** [comment] 2016-03-17 10:15
no, looks ok - did not notice any problems related to ignore (but also did not have to use `ignore` much after the dependency resolution improved)

**Comment by mattfarina** [comment] 2016-03-17 14:57
Since we have both `ignore` and `excludeDirs` I think this can be closed. If there is still an issue please re-open.

**Closed by mattfarina** 2016-03-17 14:57 UTC
Labels: awaiting feedback
