### ISSUE TITLE
Glide fails to checkout vendor packages on Windows

### ISSUE THREAD

**Issue by aboukirev** [Masterminds/glide#206] opened 2015-12-30 20:31 UTC
After #194 was fixed I started getting the following warnings a lot:
```
[INFO] Fetching updates for github.com/GeertJohan/go.rice.                                                                                                  
[WARN] Unable to checkout github.com/GeertJohan/go.rice                                                                                                     
[WARN] Update failed for github.com/GeertJohan/go.rice: fatal: could not create work tree dir 'D:\Go\src\example.com\vendor\github.com\GeertJohan\go.rice': No such file or directory                                                                                                                                     
: exit status 128                                                                                                                                           
```
This is in Windows x64 using git from MSYS2.

I was able to fix it by adding a snip of code that creates missing directory at line 497 in cmd/get_imports.go:
```
        if err = os.MkdirAll(dest, os.ModePerm); err != nil {
			Warn("Unable to create %s\n", dest)
			return err
        }
```
I wonder if it is inability of git from MSYS2 to create directory as it checks out the sources.  But this worked.

**Comment by jrick** [comment] 2015-12-30 20:32
That error is from git.

Masterminds/vcs#11

**Comment by davecgh** [comment] 2015-12-30 20:44
As @jrick notes, the issue here is the vcs package is using absolute Windows paths instead of operating like the Go tooling does where it effectively changes to the directory itself (by setting the `.Dir` field on the `exec.Cmd` type) and using a relative path.  This allows the Go tooling to avoid the need to use absolute paths and therefore it will work with msys2 git as well as git-for-windows and any other variant.

**Comment by mattfarina** [comment] 2016-01-01 13:37
So, the fix here would be to use relative paths instead of absolute ones.

That change should happen here instead of in Masterminds/vcs.

**Comment by douglaswth** [comment] 2016-02-11 01:17
I'm running into this issue trying to run Glide under Cygwin.

**Comment by mattfarina** [comment] 2016-02-11 14:34
@douglaswth what version of Glide are you running (`glide --version`)?

**Comment by douglaswth** [comment] 2016-02-11 23:15
I am seeing it with 0.8.3 and I also tried 0.9.0-rc1 with the same problem.

**Comment by mattfarina** [comment] 2016-02-11 23:31
Ah, yes. we fixed on issue inside the vcs package but the issue of relative vs absolute paths is something we'd not worked on yet.

**Comment by mattfarina** [comment] 2016-07-05 16:14
I'm going to punt this to 0.12 because we'll be making changes, sooner rather than later, to use a cache directory for resolution. I have some windows difficulties and "I think" this will make it easier.

_Note, "I think" are famous last words. I realize this and I look forward to the easy._

**Comment by mattfarina** [comment] 2016-08-18 13:38
I think this is fixed in the tip of master. I was able to reproduce these problems while moving to the use of a central user/system cache and correct the cases I found. Is this still an issue? I can no longer reproduce it.

**Comment by mattfarina** [comment] 2016-08-22 13:08
If this problem still exists please file an issue.

**Closed by mattfarina** 2016-08-22 13:08 UTC
Labels: bug

**Comment by Trane9991** [comment] 2016-09-18 17:57
Hello, 
I'm trying to run automated build on Azure WebService and I'm getting error:
```
[INFO]	--> Fetching golang.org/x/net.
[INFO]	--> Fetching golang.org/x/sys.
[INFO]	--> Fetching gopkg.in/yaml.v2.
[WARN]	Unable to checkout github.com/gorilla/context
[ERROR]	Update failed for github.com/gorilla/context: Unable to get repository
[WARN]	Unable to checkout github.com/hashicorp/go-cleanhttp
[ERROR]	Update failed for github.com/hashicorp/go-cleanhttp: Unable to get repository
[WARN]	Unable to checkout github.com/fsouza/go-dockerclient
[ERROR]	Update failed for github.com/fsouza/go-dockerclient: Unable to get repository
[ERROR]	Failed to install: Unable to get repository
Unable to get repository
Unable to get repository
```

the previous build has an error:
```
[WARN]	Unable to checkout github.com/Sirupsen/logrus
[ERROR]	Update failed for github.com/Sirupsen/logrus: Unable to get repository
[ERROR]	Failed to install: Unable to get repository
```

next time:
```
[WARN]	Unable to checkout github.com/hashicorp/go-cleanhttp
[ERROR]	Update failed for github.com/hashicorp/go-cleanhttp: Unable to get repository
[WARN]	Unable to checkout github.com/juju/ratelimit
[ERROR]	Update failed for github.com/juju/ratelimit: Unable to get repository
[WARN]	Unable to checkout github.com/ugorji/go
[ERROR]	Update failed for github.com/ugorji/go: Unable to get repository
[ERROR]	Failed to install: Unable to get repository
```

each time like 60-80% of dependencies are downloaded OK and rest of them are failing...
