### ISSUE TITLE
`glide get` should pin version by default

### ISSUE THREAD

**Issue by albrow** [Masterminds/glide#99] opened 2015-10-09 18:40 UTC
Currently, when you run `glide get`, it adds a line to glide.yaml which looks something like:

```
import:
  - package: github.com/Masterminds/cookoo
```

`glide get` should pin the version by default by including the `ref` in glide.yaml. I cannot imagine a use case where you would want to add a package to glide.yaml and *not* pin the version.

In one of my projects we are using glide and not committing the vendor directory to git. If there is no version for a package in glide.yaml, it means our builds are not reproducible. So I have had to go in to glide.yaml and manually add the version each time.

I understand that this is not the same workflow that everyone uses. If you are committing the vendor directory to version control, it certainly won't harm you to have the version pinned by default in glide.yaml.

**Comment by mattfarina** [comment] 2015-10-09 20:01
Thanks for the feedback here.

My original thought was to specify a version as a flag. For example, `glide get github.com/Masterminds/cookoo --version 1.2.0`. But, over on #96 there was a discussion of retrieving more than one dependency with `glide get`. That changes how you can handle dealing with versions.

You are very right that not specifying a version leads to unreproducible builds. This is an area we'd like to improve the experience.

**Comment by albrow** [comment] 2015-10-09 21:03
@mattfarina thanks for the quick response. I like the idea of specifying a version (or commit hash for projects not using SemVer) with the `--version` flag.

This issue still has relevance for cases where the `--version` flag is not provided. In that case, glide should assume you want the latest version and should add version information to glide.yaml to prevent the version from changing between builds. If the project is not using SemVer, `glide get` should pin `ref` to the latest commit on the master branch. If the project is using SemVer, `glide get` should add the latest major or minor version to glide.yaml. This is how bundler behaves in the ruby world and how npm behaves for javascript (except they always assume SemVer because of the way packages are added to the registry).

**Comment by technosophos** [comment] 2015-10-10 02:27
The main design of `glide get` was to mirror `go get` quite closely, but put the downloaded packages into `vendor`, and track it in `glide.yaml`. Pinning is an additional step that isn't really close to the default Go way of doing things (not that that's right -- just that it's expected).

That said, I can understand why many developers prefer to pin their dependencies. Some even want to always keep them pinned. To facilitate that, I'd be okay with a `--version` or `--pin, -p` flag. I would not be comfortable with moving the default `glide get` behavior further from `go get`, though.

I think @albrow might have given us a suitable workaround for our previous `--version` problem. If `--pin` is specified, we could simply pin _all_ of the specified dependencies.

So assume this:
```
$ go get -p github.com/foo/bar bitbucket.org/sticks/stones
```

The behavior would be to get both dependencies and then immediately ad `pin` entries for them. That would facilitate the strong pinning workflow that @albrow uses, while still staying close to `go get` and also still allowing multiple package gets.

Thoughts?

**Comment by mattfarina** [comment] 2015-10-10 11:21
Should `--pin` get the latest commit on the default branch or the latest released version?

**Comment by technosophos** [comment] 2015-10-10 17:22
What is "latest released version" in this context? Last tag?

**Comment by sdboyer** [comment] 2015-10-21 19:20
big +1 to a `--pin` option.

since your stated objective is to mirror `go get` closely, i'd say that you sorta dodge the question by just doing the same thing it does - at least as a start. so, in your example:

```
$ glide get -p github.com/foo/bar bitbucket.org/sticks/stones
```

it's just gonna grab whatever the default fetch point is, and pin at that. this seems like a good starting point?

now perhaps, in a later feature, if you want to permit specifying multiple versions and pinning at something else, you include it in the argument itself:

```
$ glide get -p github.com/foo/bar:master bitbucket.org/sticks/stones:v0.1.2
```

this obviously gets a little messier, but i think from a user perspective, just getting SOME version into the glide file is a helpful bump just by overwhelming a bit of "blank page syndrome" - to me, fixing the wrong target id seems less onerous than going through and writing them all myself, directly.

ofc, this process would have to dereference those down into immutable commit identifiers for storage in the lockfile. that's easy for now. but, when you roll in semver - which @mattfarina just told me should be soon  - that'll change this a bit. you might then, optionally, add a `--deref` flag:

```
$ glide get -p --deref github.com/foo/bar:master bitbucket.org/sticks/stones:v0.1.2
```

when the flag is present, it'll dereference the floating identifier into its underlying immutable commit id in the glide.yaml. otherwise, it records the floater.

(note that i'd also love to see more pinning-related smartness in the `guess` tool...)

**Comment by technosophos** [comment] 2015-10-30 03:14
I think that at this point we're going to follow this suggestion of pinning by default. @albrow is right that that's the best default behavior. I think we should defer till 0.8 to make sure we do this right. (0.7 will be out in the next few days)

**Comment by sdboyer** [comment] 2015-10-30 04:18
:beers:

**Comment by mattfarina** [comment] 2015-12-08 16:17
With #156 being merged `glide get` will pin by default but you can't specify a version in the package path, yet. So, I'm going to leave this open for the time being.

**Closed** 2015-12-09 15:40 UTC

**Comment by subfuzion** [comment] 2016-10-09 23:42
This is really needed. Shouldn't have to go in and edit glide.yaml as a subsequent step.

**Comment by sdboyer** [comment] 2016-10-17 19:30
@subfuzion this should've been solved last year - you're still encountering the issue on a recent version of glide?
