### ISSUE TITLE
Glide fails when a git sha ref is provided

### ISSUE THREAD

**Issue by ryanking** [Masterminds/glide#77] opened 2015-09-11 23:31 UTC
As far as I can tell, the process for updating a vendored dependency is to a git ref, it appears to not be able to update it. I'm trying to dig in an find out why, but one problem I found is that it runs a git fetch and pull, even when on a detached head, which is going to fail with git.

**Comment by technosophos** [comment] 2015-09-12 00:38
I believe that we used to do a `git fetch --all` and then do a git checkout to do this before. IIRC (and I'm working from memory here), that worked even on detached heads.

**Comment by mattfarina** [comment] 2015-09-12 01:04
I know what the issue is. Will fix it soon.

**Comment by mattfarina** [comment] 2015-09-12 02:27
Now that Masterminds/vcs#3 has been fixed can you try this again and let me know if it's fixed. The issue was in that project.

If you grab master `go get -u github.com/Masterminds/glide` you can test it instead of a binary. If you already retrieved it that way you may need to `go get -u github.com/Masterminds/vcs` first to get that fix.

Basically, `Update()` on a git repo needed to only pull when not in a detached head state. Pulling in a detached head state causes the error you saw.

**Comment by mattfarina** [comment] 2015-09-14 13:19
@technosophos should we do a new build? Maybe a 0.5.2 release? The change was in a dependency so the only change for those using a binary would be the CHANGELOG. But, it would help anyone using a binary copy rather than getting via `go get`.

Thoughts?

**Comment by mattfarina** [comment] 2015-09-14 13:19
Note, i've tested the fix and everything appears to be working.

**Comment by technosophos** [comment] 2015-09-15 15:00
Yes, we should do a release for this.

**Comment by mattfarina** [comment] 2015-09-16 16:21
0.6.0 is tag and being released. Closing with the release.

**Closed by mattfarina** 2015-09-16 16:21 UTC
Labels: bug
