### ISSUE TITLE
Wrongly pinned deps

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#61] opened 2015-08-26 01:48 UTC
with `glide.yaml`:

```
package: main
import:
  - package: golang.org/x/net
  - package: github.com/gorilla/context
  - package: code.google.com/p/cascadia
  - package: github.com/codegangsta/negroni
  - package: github.com/PuerkitoBio/goquery
  - package: github.com/gorilla/mux
  - package: github.com/boltdb/bolt
  - package: bitbucket.org/kardianos/osext
  - package: github.com/GeertJohan/go.rice
  - package: github.com/daaku/go.zipexe
  - package: code.google.com/p/go.net
```

running `glide pin` outputs:

```
$ glide pin
[WARN] Could not get commit on code.google.com/p/cascadia: Cannot detect VCS[WARN] Could not get commit on bitbucket.org/kardianos/osext: exit status 255[WARN] Could not get commit on code.google.com/p/go.net: exit status 255package: main
import:
  - package: golang.org/x/net
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/gorilla/context
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: code.google.com/p/cascadia
  - package: github.com/codegangsta/negroni
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/PuerkitoBio/goquery
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/gorilla/mux
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/boltdb/bolt
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: bitbucket.org/kardianos/osext
  - package: github.com/GeertJohan/go.rice
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/daaku/go.zipexe
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: code.google.com/p/go.net
```

It happens that `02bd0106...` is actually the git commit of the current repo, and not of any of the dependencies.

Also, notice the WARNings which are all on the same line.. difficult to read :)

**Comment by technosophos** [comment] 2015-08-26 02:31
Having trouble reproducing on master. Here's what I get with the same glide.yaml:

```
⇒  glide pin
[WARN] Could not get commit on code.google.com/p/cascadia: Cannot detect VCS[WARN] Could not get commit on bitbucket.org/kardianos/osext: exit status 255[WARN] Could not get commit on code.google.com/p/go.net: exit status 255package: main
import:
  - package: golang.org/x/net
    ref:     7654728e381988afd88e58cabfd6363a5ea91810
  - package: github.com/gorilla/context
    ref:     1c83b3eabd45b6d76072b66b746c20815fb2872d
  - package: code.google.com/p/cascadia
  - package: github.com/codegangsta/negroni
    ref:     c7477ad8e330bef55bf1ebe300cf8aa67c492d1b
  - package: github.com/PuerkitoBio/goquery
    ref:     b4440419d81240f8451a505b2f806c853bc2befc
  - package: github.com/gorilla/mux
    ref:     ee1815431e497d3850809578c93ab6705f1a19f7
  - package: github.com/boltdb/bolt
    ref:     90fef389f98027ca55594edd7dbd6e7f3926fdad
  - package: bitbucket.org/kardianos/osext
  - package: github.com/GeertJohan/go.rice
    ref:     ada95a01c963696fb73320ee662195af68be81ae
  - package: github.com/daaku/go.zipexe
    ref:     a5fe2436ffcb3236e175e5149162b41cd28bd27d
  - package: code.google.com/p/go.net
```

And I agree -- we need to fix those warnings.

**Comment by abourget** [comment] 2015-08-26 02:41
ok, it seems to report the base package's git revision, when the vendored packages are not git checkouts.. but rather only a fixed copy (like a subtree) or just some code you put up in `vendor/`.. 

I guess it's natural that git returns that revision, but it's false in this case, as it's a revision for the specified package.

**Comment by technosophos** [comment] 2015-08-26 02:55
Oh, I see... since subtree squashes the commits into the local repo's reflog, a vcs call would only see the last commit on the local repo. Any idea how to get the older repo commits on a subtree? If, for example, you know the git command, that might help. Also @mattfarina might know.

**Comment by abourget** [comment] 2015-08-26 03:14
in this particular case.. I didn't even use subtree .. I copied the files that `gb vendor` had exported from git repos.. so they were simply `.git`-less checkouts..

There wouldn't be any metadata using subtrees.. metadata would be stored in `glide.yaml`..

**Comment by mattfarina** [comment] 2015-08-26 10:35
So, if I understand it right the dependencies are vendored, that is part of the parent projects codebase rather than part of their own VCS projects. Is that right?

If so, there is no way to get a pinned version as no information is available.

The warnings may because the code is vendored and there's no local VCS information. I'll try to poke at this later today.

**Comment by abourget** [comment] 2015-08-26 13:06
yes, but I might want to pin some that *are* git checkouts, but leave those who aren't as unpinned..

I got that after running a simple `glide guess`, but it seems this failed to detect when the packages are *not* versioned (perhaps it could set `vcs: none` in that case ?).

So basically, the flow with "git archive" dumps under `vendor/` is not really functional, the moment no `.git` ,`.hg`, `.svn`, `.bzr` exist in there..

**Comment by mattfarina** [comment] 2015-08-26 13:21
@abourget For `glide update` what do you think of a flag to tell glide to update the vendored version. If the flag is present it will remove the directory in `vendor/`, fetch the repo, set the new version, and then remove the vcs directory?

**Comment by mattfarina** [comment] 2015-08-26 15:17
Since #62 is working with subtrees and 9ab138b fixed the issue of the wrong version (now it doesn't do a version if no vcs to get it from) and I added #66 to deal with the warnings I'm going to close this. If there is still an issue please re-open.

**Closed by mattfarina** 2015-08-26 15:17 UTC
