### ISSUE TITLE
`glide get` update all packages which are already installed

### ISSUE THREAD

**Issue by ninhdh0** [Masterminds/glide#348] opened 2016-03-23 10:38 UTC
How to use glide just get the package that I want and don't update all packages that are already installed?
I use `glide get` cmd, but strange that it run both `glide get` and  `glide up`

I am using `glide-0.8.3` installed by `brew`

> glide get github.com/go-ini/ini
[INFO] Preparing to install 1 package.
[INFO] Importing github.com/go-ini/ini
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/op/go-logging.
.
.
.

**Comment by james-lawrence** [comment] 2016-03-23 13:59
duplicate? https://github.com/Masterminds/glide/issues/328

**Comment by mattfarina** [comment] 2016-03-23 19:10
@ninhdh0 A few things...

1. Version 0.9.3 is in homebrew. I would suggest updating.
2. As @james-lawrence suggests, this is a duplicate of #328.
3. Glide is designed to work with versions (semver, semver ranges, tracking branches, etc). The default when no version is given is to track the tip of the default branch (usually master for Git projects). When a new dependency is fetched the versions in use need to be re-resolved to make sure the tree is using the correct versions. This is why that happens. If versions are in use this isn't as big an issue.

I'm closing because this is a duplicate.

**Closed by mattfarina** 2016-03-23 19:10 UTC
Labels: duplicate
