### ISSUE TITLE
Error with golang.org/x/text

### ISSUE THREAD

**Issue by itscaro** [Masterminds/glide#276] opened 2016-02-22 15:58 UTC
I got these errors with golang.org/x/text:

[ERROR] Error scanning golang.org\x\text: found packages text (doc.go) and main (gen.go) in ...\vendor\golang.org\x\text
[ERROR] Error scanning golang.org\x\text\language: found packages language (common.go) and main (gen_common.go) in ...\vendor\golang.org\x\text\language
[ERROR] Error scanning golang.org\x\text\unicode\norm: found packages norm (composition.go) and main (maketables.go) in ...\vendor\golang.org\x\text\unicode\norm

What does that mean?

**Comment by mattfarina** [comment] 2016-02-22 16:59
This is a duplicate of #276. Working on a fix today.

**Closed by mattfarina** 2016-02-22 16:59 UTC
Labels: duplicate

**Comment by itscaro** [comment] 2016-02-23 10:13
What is the ticket I need to follow? You quoted the same ticket here.

Thanks.

**Comment by nadermx** [comment] 2016-11-10 19:34
I'm also getting this, and as @itscaro said you refrenced the same issue @mattfarina  trying to upgrade but can't seem to figure it out.

**Comment by hstern** [comment] 2018-07-26 17:18
Was this ever fixed?
