### ISSUE TITLE
The latest PR merge breaks things due to `version` instead of `ref`

### ISSUE THREAD

**Issue by akutz** [Masterminds/glide#121] opened 2015-10-27 22:54 UTC
Hi All,

This commit (https://github.com/Masterminds/glide/commit/bb1a93462101978c3fcb1f9a44b8d2d940ed8cf1#diff-04c6e90faac2675aa89e2176d2eec7d8) breaks my build, again.

See https://travis-ci.org/akutz/rexray/builds/87783769

The emitted branch of the aliases repo does not include the commits actually there. I'm betting once I switch `ref` for `version` it will magically work. But this is really frustrating as it could have been caught with testing.

**Comment by akutz** [comment] 2015-10-27 22:59
I take that back, the latest builds apparently break it completely. *sigh* Here's a local vendor dir after updating glide locally and pulling things using `version` instead of `ref` in the `glide.yaml`:

```
[0]akutz@pax:rexray$ git --git-dir=vendor/github.com/spf13/viper/.git --work-tree=vendor/github.com/spf13/viper log -n 5 --oneline
1967d93 Fixed #36: Changed Marshal to Unmarshal throughout.
0a4a93b [110] Default Values Specify Type
3c0ff86 running tests again
09ba0a6 fixing second slice type needed
d028fd6 changing import statements back
```

Yet if we look at the remote:

```
[0]akutz@pax:rexray$ git --git-dir=vendor/github.com/spf13/viper/.git --work-tree=vendor/github.com/spf13/viper remote -v
origin	https://github.com/akutz/viper.git (fetch)
origin	https://github.com/akutz/viper.git (push)
[0]akutz@pax:rexray$ 
```

And then at my config:

```
  - package: github.com/spf13/viper
    version: support/rexray
    repo:    https://github.com/akutz/viper.git
    vcs:     git
```

And then at that branch on the remote (https://github.com/akutz/viper/commits/support/rexray):

![image](https://cloud.githubusercontent.com/assets/101085/10775177/5d484b0e-7cd4-11e5-9802-ce79211ec83c.png)

This has broken my builds, and I'm currently trying to figure out how to best backtrack to an earlier, working glide build. I don't suppose you'd reverse that merge request, would you? It appears to be FUBAR.

**Comment by akutz** [comment] 2015-10-27 23:09
Okay, it may be me? I updated Glide locally and reverted the "bad" commit, and it's actually still broken. At some point did you remove support for branch names?

```
[0]akutz@pax:rexray$ $GOPATH/bin/glide up
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/goamz/goamz.
[INFO] Fetching updates for github.com/emccode/goscaleio.
[INFO] Fetching updates for github.com/emccode/goxtremio.
[INFO] Fetching updates for github.com/akutz/golf.
[INFO] Fetching updates for github.com/go-yaml/yaml.
[INFO] Fetching updates for github.com/spf13/pflag.
[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/spf13/viper.
[INFO] Fetching updates for gopkg.in/yaml.v1.
[INFO] Setting version for gopkg.in/yaml.v2 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/goamz/goamz to d864e94f00efde9785b51e0d9f9e3ed04e2e6ecd.
[INFO] Setting version for github.com/emccode/goscaleio to ff8bf10008603307944f5b14cc2bc21bc6b411b2.
[INFO] Setting version for github.com/emccode/goxtremio to 89e87d4bdf43837a161fd36ad8dd32e0ce42ae98.
[INFO] Setting version for github.com/akutz/golf to v0.1.1.
[INFO] Setting version for github.com/go-yaml/yaml to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/spf13/pflag to b084184666e02084b8ccb9b704bf0d79c466eb1d.
[INFO] Setting version for github.com/spf13/cobra to 363816bb13ce1710460c2345017fd35593cbf5ed.
[WARN] The reference 'support/rexray' is not valid
[WARN] Failed to set version on github.com/spf13/viper to support/rexray: improper constraint: support/rexray
[INFO] Setting version for gopkg.in/yaml.v1 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Package gopkg.in/yaml.v2 manages its own dependencies
[INFO] Package github.com/goamz/goamz manages its own dependencies
[INFO] Package github.com/emccode/goscaleio manages its own dependencies
[INFO] Package github.com/emccode/goxtremio manages its own dependencies
[INFO] Package github.com/akutz/golf manages its own dependencies
[INFO] Package github.com/go-yaml/yaml manages its own dependencies
[INFO] Package github.com/spf13/pflag manages its own dependencies
[INFO] Package github.com/spf13/cobra manages its own dependencies
[INFO] Package github.com/spf13/viper manages its own dependencies
[INFO] Package gopkg.in/yaml.v1 manages its own dependencies
[INFO] Setting version for gopkg.in/yaml.v2 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for github.com/goamz/goamz to d864e94f00efde9785b51e0d9f9e3ed04e2e6ecd.
[INFO] Setting version for github.com/emccode/goscaleio to ff8bf10008603307944f5b14cc2bc21bc6b411b2.
[INFO] Setting version for github.com/emccode/goxtremio to 89e87d4bdf43837a161fd36ad8dd32e0ce42ae98.
[INFO] Setting version for github.com/spf13/pflag to b084184666e02084b8ccb9b704bf0d79c466eb1d.
[INFO] Setting version for github.com/spf13/cobra to 363816bb13ce1710460c2345017fd35593cbf5ed.
[WARN] The reference 'support/rexray' is not valid
[WARN] Problem setting version on github.com/spf13/viper: improper constraint: support/rexray (flatten)
[INFO] Setting version for github.com/akutz/golf to v0.1.1.
[INFO] Setting version for github.com/go-yaml/yaml to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Setting version for gopkg.in/yaml.v1 to b4a9f8c4b84c6c4256d669c649837f1441e4b050.
[INFO] Project relies on 10 dependencies.
[0]akutz@pax:rexray$ 
```

Note that the portion of my config using a branch name fails. I used to use them. Your documentation uses `master`. Something up?

**Comment by mattfarina** [comment] 2015-10-28 02:47
The branch issue is unexpected. I'm able to duplicate your problem and I will work on this next. This was caused by the semantic version support that recently went in. I hope to have a fix for this on Wednesday. Sorry about that.

**Comment by mattfarina** [comment] 2015-10-28 13:40
@akutz This should be fixed. I tested it the `glide.yaml` file you shared above and it's working now. If there is still a problem with this please re-open the issue.

**Closed** 2015-10-28 13:39 UTC
Labels: bug

**Comment by akutz** [comment] 2015-12-22 20:06
Hi All, 

My manager and cohort on REX-Ray, among other things, @clintonskitson noted that this appears to have regressed in 0.8.0, and was working in 0.7.2 (https://github.com/emccode/rexray/issues/221#issuecomment-166715284).

**Comment by akutz** [comment] 2015-12-22 20:55
Hi @mattfarina,

It's apparently an ordering issue with transitive dependencies. Please see this PR https://github.com/emccode/rexray/pull/237

**Comment by mattfarina** [comment] 2015-12-22 20:57
@akutz thanks. I was just running `glide up` to see if I could reproduce the issues. I'll look over there.

**Comment by akutz** [comment] 2015-12-22 20:58
Hi @mattfarina,

Yup, no worries. Please feel free to re-order the `goof` dependency where it was prior to the change in the PR, run `make deps`, and then you should see the issue crop up.
