### ISSUE TITLE
glide update stalling on windows

### ISSUE THREAD

**Issue by thinkong** [Masterminds/glide#194] opened 2015-12-28 08:41 UTC
hello 

I cloned and built glide on a windows machine 
`git glone github.com/Masterminds/glide`
`make bootstrap`
`make build`
a proper exe came out...
but when i run it it stalls

the same thing runs perfectly on linux.. 
probably something wrong with a windows build?

here is what is shown when i run `glide --debug install`

````
λ glide --debug install
[INFO] Lock file (glide.lock) does not exist. Performing update.[INFO] Fetching updates for myproj.
rem@192.168.1.10's password:
rem@192.168.1.10's password:
[INFO] Fetching updates for github.com/tealeg/xlsx.
[INFO] Fetching updates for github.com/satori/go.uuid.
[INFO] Fetching updates for github.com/mattn/anko.
[INFO] Fetching updates for github.com/daviddengcn/go-colortext.
[INFO] Fetching updates for github.com/elgs/gostrgen.
[INFO] Fetching updates for github.com/mitchellh/mapstructure.
[INFO] Fetching updates for github.com/dancannon/gorethink.
[INFO] Fetching updates for github.com/gin-gonic/gin.
[INFO] Fetching updates for github.com/julienschmidt/httprouter.
[DEBUG] ---> Inspecting d:\gopath\src\main\vendor for changes (10 packages).
[DEBUG] ----> Scanning kbo
[DEBUG] Looking in d:\gopath\src\main\vendor/myproj/Godeps/ for a Godeps.json file.
[DEBUG] Looking in d:\gopath\src\main\vendor/myproj/vendor/ for a manifest file.
[INFO] Scanning myproj for dependencies.
[DEBUG] => Scanning encoding/json
`````

**Comment by mattfarina** [comment] 2015-12-28 13:12
I have a couple questions to try and understand your setup more clearly.

1. Can you provide the output of `go env`.
2. Is your project checked out within the `GOPATH`?

**Comment by aboukirev** [comment] 2015-12-28 18:06
Same here.  My `go env` is (using MSYS2 on Windows x64 in C:\local):
```
set GOARCH=amd64                                   
set GOBIN=                                         
set GOEXE=.exe                                     
set GOHOSTARCH=amd64                               
set GOHOSTOS=windows                               
set GOOS=windows                                   
set GOPATH=D:\Go                                   
set GORACE=                                        
set GOROOT=C:\local\go                             
set GOTOOLDIR=C:\local\go\pkg\tool\windows_amd64   
set GO15VENDOREXPERIMENT=1                         
set CC=gcc                                         
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0   
set CXX=g++                                        
set CGO_ENABLED=1
```

My project is under D:\Go\src as is proper, i.e. in GOPATH.

What I noticed is that combining paths `glide` produces a mix of forward and back slashes and I know some other instances where it causes a lot of problems.  Look at the `[DEBUG] Looking in ...` in the log from original poster.  My guess is that same applies when `glide` is checking the built-in packages and results into failure to locate those.

**Comment by mattfarina** [comment] 2015-12-28 18:48
@aboukirev Thanks for the additional detail.

**Comment by mattfarina** [comment] 2015-12-29 03:07
I just pushed a change to the branch `issue/194`. Can you try that out in your windows setup? It uses `filepath.FromSlash` to switch from path to filesystem separators in the proper environments.

**Comment by aboukirev** [comment] 2015-12-29 04:41
Somewhat better (see below) but I am getting output like this
```
[WARN] Directory is missing: D:\Go\src\example.com\vendor\bytes[INFO] Scanning fmt for dependencies.  
[WARN] Directory is missing: D:\Go\src\example.com\vendor\fmt[INFO] Scanning fmt for dependencies.    
```
In the output above all path separators are correct but it looks for packages in a wrong location.  Notice also that there is no line break after warning message..

**Comment by thinkong** [comment] 2015-12-29 08:48
go env 
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\myproj
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
branch `issue/194` seems to give the same result

**Comment by aboukirev** [comment] 2015-12-29 17:21
Found it.  Lines 215 and 226 in tree.go split GOPATH and GOROOT by ':'.  In Windows colon is used to separate drive from the rest of the path.  The separator of paths is ';' semicolon.

**Comment by mattfarina** [comment] 2015-12-29 18:19
@aboukirev I thought we'd switched all the path splitting to use `filepath.SplitList` to handle different operating systems correctly. Thanks for catching that.

**Comment by mattfarina** [comment] 2015-12-29 18:46
Can you try the latest on the `issue/194` branch and let me know if this fixes the issues

**Comment by aboukirev** [comment] 2015-12-29 19:26
It works overall but I have a different issue that is MSYS2 specific, nothing to do with `glide`.  Some MSYS2 applications/scripts do not like Windows paths (it's a slow process of fixing all such instances) and git is having trouble with `chdir` to a Windows path.  Never mind that though, I'll see what I can do in MSYS2 to resolve it.

**Comment by mattfarina** [comment] 2015-12-29 20:24
@thinkong does this latest update fix your issues?

**Comment by davecgh** [comment] 2015-12-29 20:29
For reference, this branch breaks things for me on Windows.  On master with no `vendor` directory or `glide.lock` file, running `glide up` gives me:

```bash
$ glide -v
glide version 0.8.2-8-ga9410c3
$ glide up
```
> [INFO] Fetching updates for github.com/btcsuite/btclog.
> [INFO] Fetching updates for github.com/btcsuite/btcutil.
> ...
> [INFO] Scanning github.com/btcsuite/btclog for dependencies.   ***<-- hangs here***

With the `issue/194` branch I get:

```bash
$ glide -v
glide version 0.8.2-10-geee5327
$ glide up
```
> [INFO] Fetching updates for github.com/btcsuite/btclog.
> [WARN] Unable to checkout github.com/btcsuite/btclog
> [WARN] Update failed for github.com/btcsuite/btclog: fatal: could not create work tree dir 'D:\tmpgo\src\github.com\btcsuite\btcd\vendor\github.com\btcsuite\btclog': No such file or directory
: exit status 128

**Comment by aboukirev** [comment] 2015-12-29 20:37
Dave, that's exactly what I'm getting and I believe it's MSYS2 (it expects *nix paths).  Is that what you use for git?  I had troubles with MSYS2 git when building atom editor plugins and and early versions of Rust.
I can see that `glide` uses its own package to wrap calls to VCS cli.  I wonder if golang built-in tooling from `go get` could be used instead.

**Comment by davecgh** [comment] 2015-12-29 21:00
@aboukirev: Yep, I'm using MSYS2.  However, I also see the same behavior with `cmd.exe`:

> D:\tmpgo\src\github.com\btcsuite\btcd>d:\tmpgo\bin\glide.exe -v
> glide version 0.8.2-10-geee5327
> D:\tmpgo\src\github.com\btcsuite\btcd>d:\tmpgo\bin\glide.exe up
> [INFO] Fetching updates for github.com/btcsuite/btclog.
> [WARN] Unable to checkout github.com/btcsuite/btclog
> [WARN] Update failed for github.com/btcsuite/seelog: fatal: could not create work tree dir 'D:\tmpgo\src\github.com\btcsuite\btcd\vendor\github.com\btcsuite\btclog': No such file or directory
: exit status 128

**Comment by davecgh** [comment] 2015-12-29 21:50
For some additional data, I noticed the stall goes away on master if I change the `GOPATH` to the C: drive although it takes ages to scan and looks for the stdlib packages.

> [INFO] Fetching updates for time.
> [WARN] Unable to checkout time
> [WARN] Skipped getting time: Cannot detect VCS

**Comment by jrick** [comment] 2015-12-29 22:08
I also could not reproduce any stall (even with master) when both my Go installation and GOPATH were on C:

**Comment by mattfarina** [comment] 2015-12-30 00:31
If cmd.exe and MSYS2 for Git do paths differently does anyone have a pointer on how to make that work for a cli?

@aboukirev We used to use the tooling behind `go get`. But, we can't use the command itself because it doesn't support the `vendor/` directory and the libraries behind it doesn't support some of the things we need to make SemVer work. So, we moved away. I'll need to take a look at how it handles paths again.

**Comment by jrick** [comment] 2015-12-30 01:10
I don't believe there should be any difference in the way paths are handled by the two shells.  msys2 does provide a unix-like filesystem layout (the typical /usr, /etc, /bin... of the msys2 installation root) and merges it with paths for Windows drives (so C:\Users\jrick becomes /c/Users/jrick).  But I think that this distinction only matters for unix tools compiled for msys2, that have to use the unix paths or be rewritten for windows.  Environment variables should always be Windows-style (e.g. even when using the msys2 bash shell, you'd want to set GOPATH with `export GOPATH='C:\Path\To\Gopath'`) and the glide binary should only need to understand the Windows paths.

**Comment by thinkong** [comment] 2015-12-30 02:44
well.. it does look like it is the problem with msys..
using windows shell(cmd.exe) to do a glide up seems to work (kinda.. windows doesn't have ssh.. so i can't download via ssh)
i use cmder to do most of my shell stuff.. and it seems that is causing problems

**Comment by mattfarina** [comment] 2015-12-30 03:26
I think this is fixed with the latest commits. I was able to reproduce the problems in my own environment and able to see them go away with the latest commits (now on master).

If the issue persists please re-open. If there are other Windows related issues please open a new issue.

Thanks for all the help. I want Glide to work well on Windows. Providing so much information has been quite useful. Thanks.

**Closed by mattfarina** 2015-12-30 03:26 UTC
Labels: bug

**Comment by melkus** [comment] 2016-07-15 09:28
I have this problem on windows 7. What branch should I use to get it resolved?
