### ISSUE TITLE
glide get doesn't save a revision

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#368] opened 2016-04-03 06:58 UTC
When I `glide get` a new dep it is inserted into `glide.yaml` with no revision.  I don't want to track upstream HEAD.  How can I

a) ask for a specific git hash or tag?
b) ask for head "right now" but pin to that git hash?

**Comment by sdboyer** [comment] 2016-04-03 13:30
b) should be what happens right now - it should update both `glide.yaml` with the `HEAD` of the specified project, and then recompute `glide.lock`. That's what it does for me when I test, anyway. You're on the most recent glide, yes?

a) is something we oughtta support, probably via a `go get github.com/foo/bar@tag`...just, haven't gotten there yet. I think?

**Comment by thockin** [comment] 2016-04-03 15:39
It didn't put a version in glide.yaml, so the next update operation will
pick a new version, won't it?

**Comment by sdboyer** [comment] 2016-04-03 20:37
ahh, i see what you mean. 

so, first, a quick distinction: if you're running a `glide install`, that just reads the lock file and ensures that the vendor directory reflects it. no changes - so, yeah, it's pinned.

if, however, you're running a `glide update`, then it'll update it. ...even if you didn't specify it for update. same goes for running `glide get` on a totally unrelated package. i don't think this is intended behavior, but the Matts would have to confirm. IMO, though, it's a bug - pinned versions shouldn't change unless the user explicitly requests it.

FWIW, that *will* be how it works when we swap in the [`vsolver`](https://github.com/sdboyer/vsolver) engine. Only if you specifically request an upgrade, or if the algorithm _has_ to change the version in order to find a solution, will a pinned version be changed.

Not sure how entrenched this issue is - and, thus, if we'd be able to get to it before we swap in the new engine.

**Comment by ches** [comment] 2016-04-04 17:53
@sdboyer When you say "pinned" with regard to integrating the solver, I assume that means "there is a version already in the lock file", correct? My expectation from similar tools is that bare `glide get` would not put any version spec in `glide.yaml`, but it would result in the version (the revision ID of current HEAD) being stored in the lock file. Then I should be able to specify a scoped update for a different package like `glide update someotherpackage`, and Glide will *not* try updating any package other than `someotherpackage`, and its deps if needed. If updating `someotherpackage` would require updating another dependency that's locked to a specific revision, it will fail with the solver reporting some information about the version constraint that would need to be loosened.

I believe that's what you're saying. And completely agree, the current tendency for almost any Glide operation to "consider" and potentially update anything in the graph is awfully confusing, and risky (see #328, for one).

**Comment by sdboyer** [comment] 2016-04-04 18:22
@ches 
>  When you say "pinned" with regard to integrating the solver, I assume that means "there is a version already in the lock file", correct?

yep. that's the meaning of pinned in the solver - and in glide right now, as well.

> My expectation from similar tools is that bare glide get would not put any version spec in glide.yaml, but it would result in the version (the revision ID of current HEAD) being stored in the lock file.

IMO, it *should* put something into the manifest. (Otherwise, the lockfile isn't fully recreatable from the manifest - and not maintaining that as an expectation is horrifying). It should just identify the current branch tip, aka HEAD. glide does this now.

> Then I should be able to specify a scoped update for a different package like glide update someotherpackage, and Glide will not try updating any package other than someotherpackage, and its deps if needed. If updating someotherpackage would require updating another dependency that's locked to a specific revision, it will fail with the solver reporting some information about the version constraint that would need to be loosened.

eeeeexactly. i'm actually writing those very failure messages right now :)

**Comment by mattfarina** [comment] 2016-04-05 13:35
There is a way for `glide get` to put version information into the `glide.yaml` file.

```sh
$ glide get github.com/coreos/etcd#v2.3.1
```

The `glide get` command can get one or more dependencies. Each dependency has it's location and then an optional `#` followed by any [version](http://glide.readthedocs.org/en/latest/versions/) Glide works with.

In the etcd example it's a tag name. When the `glide.lock` file is generated it will have the associated commit id for that tag.

Does that help?

**Comment by mattfarina** [comment] 2016-04-05 13:45
I should also note that it's acceptable manually edit `glide.yaml` files.

I've been known to run `glide init` to generate the initial `glide.yaml` file and then edit it to add the [versions or ranges](http://glide.readthedocs.org/en/latest/versions/) I wanted to use. I prefer to have versions or ranges in my `glide.yaml` file as they are easier to understand than revisions. While this is my workflow I know now everyone will use it.

**Comment by sdboyer** [comment] 2016-04-05 13:54
ahhh, it was `#` - i tried `@`. (i imagine that's not available to us b/c it would get nasty w/ the URI-like structure of package names).

should probably mention this in the `glide get --help` docs :)

**Comment by thockin** [comment] 2016-04-05 15:36
I don't have a particular revision I want to use, I just want glide to take
whatever is head RIGHT NOW and lock to that, so it never changes unless I
ask for a change, in which case I am likely to repeat this process.

Can we add a --lock-to-now flag or something?

**Comment by ches** [comment] 2016-04-05 15:50
> The `glide get` command can get one or more dependencies. Each dependency has it's location and then an optional `#` followed by any version Glide works with.

Right, I had found the hash syntax (somewhere) and was aware of it, @sdboyer makes a fair point that it's a bit hard to find currently. My expectation/question was that/if a bare `glide get` or just putting a package into `glide.yaml` with no version should result in it locking to current `HEAD` revision in the lock file, and staying that way unless subsequently updated directly, or by way of updating another dependency that depends on it. I believe that's exactly what @thockin is asking for and also the behavior that @sdboyer is suggesting here when the solver is integrated (aside from possibly putting some version in `glide.yaml` automatically as well?).

That is riskier than setting a version constraint explicitly from the start of course, but if updates are scoped to usually one or a select few packages at once (strongly discouraging the practice of ever doing a broad `glide update` of everything), it's usually quite manageable.

Sorry for belaboring the discussion, not sure if I've added to it or taken it into the weeds at this point :innocent:

**Comment by mattfarina** [comment] 2016-04-05 17:12
@thockin to ferret out your thinking a little more, would you want it to grab the latest stable release if there was a release otherwise the latest commit rev? Or, just the latest rev?

I'm also thinking about adding a way for `glide update` and `glide get` to not update the entire tree but only specified packages and their direct dependencies. Thoughts?

**Comment by thockin** [comment] 2016-04-05 17:47
For a lot of packages there just isn't a tag or anything to use, so we just
want "head as of right now".  For those packages that have tags, maybe
offering a list of tags would be nice, but this again goes to some
interactive mode.

If I say `glide get --interactive example.com/foo/bar` and it offered me
"HEAD" vs "pin to hash abcdef12345 (current head)" vs "tag v1.2.3" vs
"branch release-1.2", that would be pretty awesome.  But the minimum viable
solution would simply be to say "you didn't ask for a specific tag, so I am
assuming you want HEAD" with an optional flag `--lock-to-now` which would
say "you didn't ask for a specific tag, so I am assuming you want hash
abcdef12345 (current head)"

I'm trying to be minimal in what I ask for :)

**Comment by technosophos** [comment] 2016-04-05 17:49
It sounds like the original request was merely to make it possible to tell Glide to pin the `glide.yaml` to a VCS commit ID (e.g. explicitly set `version: <SHA>`. I wouldn't mind adding that as a flag to `glide get`, but that is the sort of thing that I thought we were trying to steer people away from. Ultimately, everyone is healthier if we set this to SemVer (range) instead of to VCS identifiers.

When it comes to intuitions about whether we should track head or automatically pin, you will find there are two fairly vocal sides on this one. (A read through the issue queue and Gitter backscroll will show this). Some people want the `go get`-like behavior of tracking master by default. Others favor stability. While both can be done explicitly, it's tough to decide which should be default.

I'd be most comfortable with just adding a flag to `glide get` that instructs glide to pin the `glide.yaml` to the current commit. That will let people who want that behavior be able to get it, but it won't defeat the push to stop using commit IDs and start using SemVer ranges.

**Comment by thockin** [comment] 2016-04-05 17:56
I agree.  Operating like `go get` is the right thing to do.  I just want a
flag that I can use to opt into (what we consider to be) sane behavior :)
 I understand that "sane" is in the eyes of the beholder.

**Comment by ches** [comment] 2016-04-05 18:08
> I'm also thinking about adding a way for `glide update` and `glide get` to not update the entire tree but only specified packages and their direct dependencies. Thoughts?

I consider this critical beyond the immediate term, personally. `glide update` updating the entire tree is like chaos, it allows the surface area of potential breaking changes to be so wide in a project with many dependencies. If the project is security-sensitive, for instance, then I want to scope my updates as narrowly as possible so that it's reasonable to vet the changes I'm pulling in at once. (Personally I want this in just about any project—no whack-a-mole of build breakages, only the components I knew would be affected by the one dep I'm willfully updating because of a fix or new feature. SemVer violations do occasionally happen, too).

> I wouldn't mind adding that as a flag to `glide get`, but that is the sort of thing that I thought we were trying to steer people away from. Ultimately, everyone is healthier if we set this to SemVer (range) instead of to VCS identifiers.

This seems redundant if the revision is already what's written to the lock file by default when you `glide get` without a version. Redundant **if** that dep doesn't get updated again unless I ask it to, i.e. again support for `glide update somepackage` and that being strongly encouraged as common usage of the `update` command.

**Comment by ches** [comment] 2016-04-05 18:24
@mattfarina Is there a ticket yet specifically for the scoped `glide update somepackage` functionality? That seems to be the crux of what @sdboyer and I ended up getting into here and advocating, and it's somewhat off topic…

I *think* it can sort of be faked right now by changing a version constraint for a single package in `glide.yaml`, and doing `glide install`, right? The version could be `master` if you want to track `HEAD` similar to `go get`…

**Comment by thockin** [comment] 2016-04-12 22:27
Any update on the ability to save "head as of now" in a get?

**Comment by sdboyer** [comment] 2016-04-13 06:58
@thockin your request here really ends up having more to do with how `glide update` works than `glide get`, no? Because you want to be pinned to whatever rev the upstream project's HEAD happens to be when you run it, and not have that change without it being explicitly requested. If `glide update` were scoped to only operate on specific projects, then 'pinning' by having that information solely in the lock should be sufficient. No?

Because, just to be clear, `glide get` *does* save the project/package to `glide.yaml`. and if you specify a revision that you want to be hard-locked to, e.g., `glide get github.com/foo/bar#bcacb06fecaeec8dc42af03c97c6949f4b05c74c`, then it'll drop that rev into `glide.yaml`. But for glide to go the extra step of *defaulting* to saving the rev into `glide.yaml` is making a poor workflow choice, I think - in terms of the metaphors from my article, it's choosing the "demon's roulette" approach, rather than the "hitch a ride" approach. And demon's roulette is not a sane default - it only seems like one if `glide update` doesn't respect what's pinned in `glide.lock.`

...I hope? :grin:

**Comment by mattfarina** [comment] 2016-04-13 16:08
@thockin I have some ideas on how to get there. Before I work on that I'm making changes to the `vcs` package to support the work here. Once that has a release (hopefully next Monday or Tuesday) I'm going to switch to some work here.

**Comment by thockin** [comment] 2016-04-13 16:19
@sdboyer I'm trying to ask for small, deliverable changes so that I can actually use glide O(soon).  Yes, I agree it is doing more work than it should right now, but I can live with that in exchange for getting off of godep.

I don't buy the "demon's roulette" argument, or at least, it's not particularly weighty.  We test everything anyway, so it's not a huge deal.  But let me put it another way - if glide were to offer me a better choice, something like "at the most recent semver tag" instead of "head right now", I would take that choice.  Or another alternative: FORCE me to specify a version.  If I want to use "floating head" (which is the default and is, IMO, insane) I need to say `github.com/foo/bar#HEAD` or `--floating-head` something.  This way I get an error on a `get` and I am forced to go look at the repo and decide what tag I want to use.  Of course, github makes it hard to see what hash is "current head" without checking the repo out, which is further pain.

**Comment by sdboyer** [comment] 2016-04-13 16:58
> I'm trying to ask for small, deliverable changes so that I can actually use glide O(soon).

Sure, quite fair 😀 we'll see where @mattfarina lands on this. 

> I don't buy the "demon's roulette" argument, or at least, it's not particularly weighty. We test everything anyway, so it's not a huge deal.

OK. I mean, for now at least, it's primarily an internal signaling issue for your folks - an indication of *how* kubernetes intends to follow a dependency. And really, when it comes to how y'all communicate internally, that really ought to be up to you. (And yeah, if you rigorously test everything internally, you're mitigating some of the other effects.)

In the bigger picture, it's less about your internals, and more about anyone who might be importing kubernetes - having revs in the `glide.yaml` forces everyone else into lock-step. I realize that's a down-the-road concern for you (at least, it would be for me if our positions were reversed), but causing *more* revs to make it into `glide.yaml`s is systemically harmful, and thus something I'd rather avoided.

To that end...

> if glide were to offer me a better choice, something like "at the most recent semver tag" instead of "head right now",

I'd agree that this is sanest - try to pick the most recent semver, and if not that the most recent version, and if not that then the default branch...some kind of cascade like that. Right now, though, the combination of:

* Picking a branch - a floating version - by default
* Not allowing `glide update` to take arguments

Creates an awkward situation. Both of them need to be addressed; dealing with either should mitigate the nasty confluence that currently exists.

**Comment by thockin** [comment] 2016-05-12 05:40
A month later, any update on this?  We've moved our repo to vendor/ with godep, which continues to be somewhat painful.

**Comment by sdboyer** [comment] 2016-05-16 15:42
@thockin afaik, this will be addressed by the new engine (#384 is the first PR), but idk if it's being worked on under the current paradigm.

I was out at a conference last week, and a few things may prevent tons of progress this week, but the ball is rolling.

**Comment by thockin** [comment] 2016-05-16 16:50
I am literally fighting back the hordes who want to switch Kubernetes to
Glide.  Just waiting on it actually *working* for us :)

**Comment by sdboyer** [comment] 2016-05-17 11:59
hordes is good 😸 

if any horde members are feeling particularly impatient, they can always come help out with glide/vsolver :)

**Comment by kimamula** [comment] 2016-05-22 12:28
I found that when I download a package with `glide get --strip-vcs` and then download another package with `glide get --strip-vcs`, the version for the first downloaded package in `glide.lock` is updated to the commit hash of my own project.

The direct cause of this problem is the implementation of `GitRepo#Version()`, which returns the commit hash of the ancestor's directory in the absence of `.git` in the downloaded package's directory.
https://github.com/Masterminds/vcs/blob/master/git.go#L163-L170

Can I expect this to be solved by @sdboyer's work as well?

**Comment by sdboyer** [comment] 2016-05-22 17:27
@kimamula yep, it will be. vsolver doesn't operate directly within the `vendor/` dir, so while that issue would still exist in the underlying library, it wouldn't manifest in the new system.

**Comment by kimamula** [comment] 2016-05-22 23:30
That's great, thanks!

**Comment by dmitris** [comment] 2016-10-13 14:18
adding my modest "+1" for the request to make 'glide get' to insert the dependency with the git SHA1 that it currently finds in the $GOPATH or that you pass as an option on the command line.  Something like `glide update -version cff893e7f9fc3999fe4f1f50f5b504beb67e1164 github.com/Masterminds/vcs` would also be great for updating glide.yaml to the newer versions of the package.  

So far we've been using `glide init` to set up the initial version of glide.yaml but afterwards we manually edit the file to add version field (as well as repo - for mirrors).

**Closed** 2024-05-31 15:24 UTC
